sudo: required
language: python
addons:
  apt_packages:
  - pandoc
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install tox==2.3.1
- pip install tox-travis==0.8
- pip install pypandoc

script:
- tox
branches:
  only: master

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git tag -a v$(python setup.py --version) -m "Travis build $TRAVIS_BUILD_NUMBER pushed
  a tag."
- git push origin --tags
- git fetch origin

deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist
    user: "trustpilot"
    password:
      secure: oru3V/7Rw8PsLBBId2pj+iTNiQkxDAyUqa+zMUjD75G/uxHsrEGdaYo1Em/hb1z2ijhJqfQkD/ul4vQRW8/f+GVG57QVLiPpz4z8K/reWfeG+qnk2eYp0UIgf54ui8ZhgX6gGFOW4KqAKTBfjUIfDM/7Or5lPOJvh8dAOpLDLmPMtRcIWXVw2KzHlOjy5UfrkIpOw0gzUfsE6CWFZ6RwPGWkNfT2E5dO1zYUup6i107xc+SMGIFqz7oLNnctofARjU7RY3eOz8avlnErYYNHo5/4JhmqRqYFeG3UWaoheQIxTnwETDTcNTFwMmDrlQK/00weP9KMyT2/Fq5WMKginl0a0MWxOps9uzc9cQmSqlFdxQhM77nu539twxNHF96EUsS3FWbcVl7NNjxXnIjS1j24gDXDhy2KbvDu2Kbs0paQb7o5Oi04hMoE8y/BvRcP1l2RWFjbjTxqBOPCdfQur80sdPMj1SoDAbr0DW5tf6dAUd7ES/Iz95KsdYEQPPaLpRwWFQHiXHI1a5SFCOAuYkloThhJy+tKncBuzCxsyVpAcJ2mQRvTDCoro0yVswR67dQleT5N/Np13aFIIBby/fY2OLZwthUoOsAyrdIjoMg+zh1aJ6XVnhNv3SjYMsCDIukS4qOm34f2ssMg1M37Lftz9SnLc3mn6v54wvMzxww=
    on:
      tags: false
      branch: master
      repo: trustpilot/python-denv
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: releases
    skip_cleanup: true
    api-key:
        secure: E5+U/abd1qohQ9QSILPlgwBC/q2gw7w2ofIjGKoN/BYDSVjIni+Z4V42VwGmNU3FKG5mrFSRJLVMEt3f8FfkE/AC28Fkh24B/9ejiz+J+Jhi0Kw17ekC3UeQxsyeKY855xSvzWsNcmC4EkbMFenOxi6QDsaZOBrd255UAkwRP7rTiKUDNRGk61p43ND0uJ87Pn+Nq+4+d6VdjQnWW8yLxYnmkwmc+qC0SyizZpMf8SQVfNQ2gOLKixjM02UF0YOpvB9EbMdLsM+gYkkaDdKNeshK41Xje+X3p2dLWn3YvKTRJ66qvx1Asir3IC0T4MMM4Jua01T/lUUiI6ruvbHaHzikOp0Z+Ee/5mr+RC9uMMC85NkhevnU4loayJ7he1TGG+fOewx34xmeYT4EOFMvHx/RkcOHarZ2r1HBQwP/36fiPy5uJI/rrdMl5upJhdrP3CvlYymu0u6X7ImEzBM3ViPhD1kMdHkgykYRocPK1uykqbHdD1SMWolES10ygR2TJH1d4x37RLXfKObwliPFs7X17Jj+qCD/MvKAt1/aNp+1LQ8AR1bXH8uS8ZV4R6Vt6nNFb9GOUu0mpORV5Az+cVko8ObT4QUgy/sZPL1Xtek9d2GyXCGM0jxp39ErBz8i+Fdx1dJlxe06AHMGuAGFFk3mrlFN0Do3f9EHi3yH4QA=
    file_glob: true
    file: dist/*
    on:
      tags: false
      branch: master
      repo: trustpilot/python-denv
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

