sudo: required
language: python
addons:
  apt_packages:
  - pandoc
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install tox==2.3.1
- pip install tox-travis==0.8
- pip install pypandoc

script:
- tox
branches:
  only: master

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git tag -a v$(python setup.py --version) -m "Travis build $TRAVIS_BUILD_NUMBER pushed
  a tag."
- git push origin --tags
- git fetch origin

deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist
    user: "trustpilot"
    password:
      secure: eJbMx8ZX8mm/NUIi+zD6Yp39OkPTIATEZFFfsxpYAkjiCQW//srE+xsLz48ZtbT384wNwqbApuoLGsR3HI49BRL2LyOJqh8gSIElZui+t5XeP6C8DQSq9OCbvKHtDFsr6Nr39u7wh27F+2ZbAScnTU6gPDQ0UT64AIPvUMya+4Tog5uen+Dh5hgV/YWSb+tNPC6lmHUvwYNkfEAe9KppwyMlzwMYqfkZ5H8GiL5vJa5azM0q2fhmb4gGTgY4NeGvdBSerH93YCswN5cslfRQBVQb1P0c1vC0O2h181wwHZyOrjeIdIq1eRGlU32OH9lC21Yd9085KhFteCrm/u8AOXVYPdVFrj1poWeUCGbQGjH7xgNzHd2rlkg2ZN9snioNp/jRLscJRYFUAA4yZ8tiNZcVec1UyysSO8ztRd0/6IZgx9mgjYQsKY+D4YYwl0U9QLI0667UB6WWr2AEzk5HbBMATRuG4ToG0hh7TT0U2b5ylz8izgDSxF9BYhG7+roYd+Tp6g8N4GrOE1sCDsTdeBabjK5q4tzlX+2MFfigh2b1haO/ZxV/cylj3nrF6w82ByBX+KYoKIdN3N35MkzqQGvR8fyD3IHhsWJfBQ9Lcl4tySy5LoPM1fvHUNlWOc6El8KUX8+2DmJVVv+ZIMNlvUeFkccAcvm80Ydr9YpFalA=
    on:
      tags: false
      branch: master
      repo: trustpilot/python-denv
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: releases
    skip_cleanup: true
    api-key:
      secure: E5+U/abd1qohQ9QSILPlgwBC/q2gw7w2ofIjGKoN/BYDSVjIni+Z4V42VwGmNU3FKG5mrFSRJLVMEt3f8FfkE/AC28Fkh24B/9ejiz+J+Jhi0Kw17ekC3UeQxsyeKY855xSvzWsNcmC4EkbMFenOxi6QDsaZOBrd255UAkwRP7rTiKUDNRGk61p43ND0uJ87Pn+Nq+4+d6VdjQnWW8yLxYnmkwmc+qC0SyizZpMf8SQVfNQ2gOLKixjM02UF0YOpvB9EbMdLsM+gYkkaDdKNeshK41Xje+X3p2dLWn3YvKTRJ66qvx1Asir3IC0T4MMM4Jua01T/lUUiI6ruvbHaHzikOp0Z+Ee/5mr+RC9uMMC85NkhevnU4loayJ7he1TGG+fOewx34xmeYT4EOFMvHx/RkcOHarZ2r1HBQwP/36fiPy5uJI/rrdMl5upJhdrP3CvlYymu0u6X7ImEzBM3ViPhD1kMdHkgykYRocPK1uykqbHdD1SMWolES10ygR2TJH1d4x37RLXfKObwliPFs7X17Jj+qCD/MvKAt1/aNp+1LQ8AR1bXH8uS8ZV4R6Vt6nNFb9GOUu0mpORV5Az+cVko8ObT4QUgy/sZPL1Xtek9d2GyXCGM0jxp39ErBz8i+Fdx1dJlxe06AHMGuAGFFk3mrlFN0Do3f9EHi3yH4QA=
    file_glob: true
    file: dist/*
    on:
      tags: false
      branch: master
      repo: trustpilot/python-denv
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

