sudo: required
language: python
addons:
  apt_packages:
  - pandoc
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install tox==2.3.1
- pip install tox-travis==0.8
- pip install pypandoc

script:
- tox
branches:
  only: master

after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git tag -a v$(python setup.py --version) -m "Travis build $TRAVIS_BUILD_NUMBER pushed
  a tag."
- git push origin --tags
- git fetch origin

deploy:
  - provider: pypi
    skip_cleanup: true
    distributions: sdist
    user: "trustpilot"
    password:
      secure: eJbMx8ZX8mm/NUIi+zD6Yp39OkPTIATEZFFfsxpYAkjiCQW//srE+xsLz48ZtbT384wNwqbApuoLGsR3HI49BRL2LyOJqh8gSIElZui+t5XeP6C8DQSq9OCbvKHtDFsr6Nr39u7wh27F+2ZbAScnTU6gPDQ0UT64AIPvUMya+4Tog5uen+Dh5hgV/YWSb+tNPC6lmHUvwYNkfEAe9KppwyMlzwMYqfkZ5H8GiL5vJa5azM0q2fhmb4gGTgY4NeGvdBSerH93YCswN5cslfRQBVQb1P0c1vC0O2h181wwHZyOrjeIdIq1eRGlU32OH9lC21Yd9085KhFteCrm/u8AOXVYPdVFrj1poWeUCGbQGjH7xgNzHd2rlkg2ZN9snioNp/jRLscJRYFUAA4yZ8tiNZcVec1UyysSO8ztRd0/6IZgx9mgjYQsKY+D4YYwl0U9QLI0667UB6WWr2AEzk5HbBMATRuG4ToG0hh7TT0U2b5ylz8izgDSxF9BYhG7+roYd+Tp6g8N4GrOE1sCDsTdeBabjK5q4tzlX+2MFfigh2b1haO/ZxV/cylj3nrF6w82ByBX+KYoKIdN3N35MkzqQGvR8fyD3IHhsWJfBQ9Lcl4tySy5LoPM1fvHUNlWOc6El8KUX8+2DmJVVv+ZIMNlvUeFkccAcvm80Ydr9YpFalA=
    on:
      tags: false
      branch: master
      repo: trustpilot/python-denv
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: releases
    skip_cleanup: true
    api-key:
      secure: SX/mRoOZLMRDp46FvCr5AFeimF1lfWjbrAKL2Exm8sOo80W23+vyfgCucdjR1nshHDvo0jXWGs1bn7dVrt7/0dwshMENgKKrnUgHnrblrWbifSczHhijtAxJZ7OV+ZteTJcYDpQ4X+8YWr6Gz/+GFteP31N3bdCVgpvueJBWq5RApLTX/GunBC4JBHW3nXJfAEEIM+MB0KaJolkWi9FmcDnbqZmauzu0oI3U+Ev/U4UKgIGA5Nh1g4sx4APFbpPXw1zPFhBiY4LFUdVbsz08SORUJkGrrIoUvpxZX99qt5zH6efhMDpMWO7Kv3zmoBv1o80YuYNaCJapYiK1TGAy16CkW99ZXHcX8DrtKC8qHs5lgKB1VOGh6X/7hAi8eqQIopSNN4PnA0MH/NOLCgdoa52Kd2S1G+/5rx849UfVNJpg8csFrdj4M/yydcNOL7CNDmlsKr3yxEN/vkCisTqv9uwU3YkhTKB0JtKgmEAV/TG9qeQ1+6j2hwPHj/1/E37bcRybOUCfkZYlbKF4b91HGEmDFH1hcURzPn3bAWqtyEVhtZaKW9DBBzTELUbbC3VEMumZBdwvL/lyDH3YK2PpyTDk0MQQ7OqxRtwduWnlrS4bRE0Zjam+Qq7A5OP2eLyXi9vm4jHuoUEzEDxZR4XjWz7Au5QpZOoxvanGuCBJlRk=
    file_glob: true
    file: dist/*
    on:
      tags: false
      branch: master
      repo: trustpilot/python-denv
      condition: $TRAVIS_PYTHON_VERSION = "2.7"

